example/Szl.MvcDemo/Controllers/BaseController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.Routing;
using Szl.MvcDemo.Szl;

namespace Szl.MvcDemo.Controllers
{
    public class BaseController : Controller
    {

        public EnrollmentState EnrollmentState
        {
            get { return VeryImpressiveInMemoryDatabase.EnrollmentState; }
        }

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {

            if (UserClickedBack())
            {
                filterContext.Result = Back();
                filterContext.Result.ExecuteResult(ControllerContext);
                return;
            }


            var state = GetCurrentBoundAction();

            var stateMachine = GetStateMachine();
            var attemptedState = stateMachine.GetStateForAction(state);
            if (attemptedState == null &&
                !(state.Action == "Route" && state.Controller == "Route"))
            {
                filterContext.Result = Redirect("/route");
                filterContext.Result.ExecuteResult(ControllerContext);
                return;
            }
        }

        private BoundAction GetCurrentBoundAction()
        {
            var action = new BoundAction
            {
                Action = ControllerContext.RouteData.Values["action"].ToString(),
                Controller = ControllerContext.RouteData.Values["controller"].ToString(),
                Params = HttpContext.Request.QueryString.ToRouteValueDictionary()
            };
            return action;
        }

        private DemoStateMachine GetStateMachine()
        {
            return StateMachineBuilder.GetStateMachine(EnrollmentState);
        }

        protected virtual bool UserClickedBack()
        {
            var backButtonClicked = ControllerContext.RequestContext.HttpContext.Request.Form["BackButtonClicked"];
            bool retval;
            return bool.TryParse(backButtonClicked, out retval) && retval;
        }

        protected virtual RedirectToRouteResult Next()
        {
            var stateMachine = GetStateMachine();

            var currentAction = GetCurrentBoundAction();
            var currentState = stateMachine.GetStateForAction(currentAction);

            var nextState = (ActionableSzl)stateMachine.GetNextState(currentState);
            var nextAction = nextState.BoundAction;

            return RedirectToAction(nextAction.Action, nextAction.Controller, nextAction.Params);
        }

        protected virtual RedirectToRouteResult Back()
        {
            var stateMachine = GetStateMachine();

            var currentAction = GetCurrentBoundAction();
            var currentState = stateMachine.GetStateForAction(currentAction);

            var previousState = (ActionableSzl)stateMachine.GetPreviousState(currentState);
            var previousAction = previousState.BoundAction;

            return RedirectToAction(previousAction.Action, previousAction.Controller, previousAction.Params);
        }

        protected virtual RedirectToRouteResult RouteToFurthest()
        {
            var stateMachine = GetStateMachine();

            var state = (ActionableSzl)stateMachine.GetFurthestState();
            var action = state.BoundAction;

            return RedirectToAction(action.Action, action.Controller, new RouteValueDictionary(action.Params));
        }
    }
}

example/Szl.MvcDemo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Szl.MvcDemo.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            VeryImpressiveInMemoryDatabase.Guids.Add(Guid.NewGuid());

            var model = new IndexModel
            {
                Message = "Index",
                Guids = VeryImpressiveInMemoryDatabase.Guids
            };
            ViewBag.IsIndex = true;
            return View(model);
        }
    }

    public class IndexModel
    {
        public string Message { get; set; }
        public List<Guid> Guids { get; set; }
    }
}

example/Szl.MvcDemo/Controllers/ProgramController.cs
using System.Web.Mvc;

namespace Szl.MvcDemo.Controllers
{
    public class ProgramController : BaseController
    {
        public ActionResult Step1(int programId)
        {
            return View(new ProgramStep1ViewModel { ProgramId = programId});
        }

        [HttpPost]
        public ActionResult Step1(ProgramStep1ViewModel viewModel)
        {
            return Next();
        }

        public ActionResult Step2(int programId)
        {
            return View(new ProgramStep2ViewModel { ProgramId = programId });
        }

        [HttpPost]
        public ActionResult Step2(ProgramStep2ViewModel viewModel)
        {
            return Next();
        }

        public ActionResult Step3(int programId)
        {
            return View(new ProgramStep3ViewModel { ProgramId = programId });
        }

        [HttpPost]
        public ActionResult Step3(ProgramStep3ViewModel viewModel)
        {
            return Next();
        }
    }

    public class ProgramViewModel
    {
        public int ProgramId { get; set; }
    }

    public class ProgramStep3ViewModel : ProgramViewModel
    {

    }

    public class ProgramStep2ViewModel : ProgramViewModel
    {
    }

    public class ProgramStep1ViewModel : ProgramViewModel
    {

    }
}

example/Szl.MvcDemo/Controllers/RouteController.cs
using System.Web.Mvc;
using System.Web.Routing;

namespace Szl.MvcDemo.Controllers
{
    public class RouteController : BaseController
    {
        [Route("route")]
        public ActionResult Route()
        {
            return RouteToFurthest();
        }
    }
}

example/Szl.MvcDemo/Controllers/StateController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Szl.MvcDemo.Controllers
{
    public class StateController : Controller
    {
        [Route("reset")]
        public ActionResult Reset()
        {
            VeryImpressiveInMemoryDatabase.Guids = new List<Guid>();
            var state = VeryImpressiveInMemoryDatabase.EnrollmentState;
            state.AllowBlockedNode = false;
            state.NumberOfPrograms = 0;
            state.Dirty = true;

            return Redirect(Request.UrlReferrer.ToString());
        }
    }
}

example/Szl.MvcDemo/Controllers/WizardController.cs
using System.Web.Mvc;

namespace Szl.MvcDemo.Controllers
{
    public class WizardController : BaseController
    {
        public ActionResult Step1()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Step1(Step1ViewModel viewModel)
        {
            return Next();
        }

        public ActionResult Step2()
        {
            return View(new Step2ViewModel {UnblockBlockNodes = EnrollmentState.AllowBlockedNode});
        }

        [HttpPost]
        public ActionResult Step2(Step2ViewModel viewModel)
        {
            EnrollmentState.AllowBlockedNode = viewModel.UnblockBlockNodes;
            EnrollmentState.Dirty = true;
            return Next();
        }

        public ActionResult Step3()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Step3(Step3ViewModel viewModel)
        {
            EnrollmentState.NumberOfPrograms = viewModel.NumberOfPrograms;
            EnrollmentState.Dirty = true;
            return Next();
        }
    }

    public class Step3ViewModel
    {
        public int NumberOfPrograms { get; set; }
    }

    public class Step2ViewModel
    {
        public bool UnblockBlockNodes { get; set; }
    }

    public class Step1ViewModel
    {

    }
}

example/Szl.MvcDemo/Views/Home/Index.cshtml
@model Szl.MvcDemo.Controllers.IndexModel

<h2>@Model.Message</h2>

<ul>
    @foreach (var guid in Model.Guids)
    {
        <li>@guid</li>
    }
</ul>
<div>
    @Html.ActionLink("To The Wizard!", "Route", "Route")
</div>

example/Szl.MvcDemo/Views/Program/Step1.cshtml
@model ProgramStep1ViewModel

<p>Program @Model.ProgramId:  Step 1</p>

example/Szl.MvcDemo/Views/Program/Step2.cshtml
@model ProgramStep2ViewModel

<p>Program @Model.ProgramId: Step 2</p>

example/Szl.MvcDemo/Views/Program/Step3.cshtml
@model ProgramStep3ViewModel

<p>Program @Model.ProgramId: Step 3</p>

example/Szl.MvcDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

    <title>Szl</title>
</head>
    <body>
        <div style="margin: auto; min-width: 500px; width: 50%">
            <h1>Szl</h1>
            <div>
                @RenderBody()
            </div>
            <div>
                @Html.ActionLink("Reset", "Reset", "State", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </body>
</html>

example/Szl.MvcDemo/Views/Shared/_StepsLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    var queryString = Html.ViewContext.RequestContext.HttpContext.Request.QueryString;
    var simpleDictionary = new Dictionary<string, object>();
    foreach (var k in queryString.AllKeys)
    {
        simpleDictionary[k] = queryString[k];
    }
    var queryDictionary = new RouteValueDictionary(simpleDictionary);
}

<div>
    @using (Html.BeginForm(null, null, queryDictionary, FormMethod.Post, null))
    {
        @Html.Hidden("BackButtonClicked", false)
        @RenderBody()
    }
</div>

<style>
    .current {
        font-size: 20em;
    }
</style>

<footer>
    <div>
        <span>
            <button type="button" class="btn btn-default" onclick="back()">
                Back
            </button>
        </span>
        <span>
            <button type="button" class="btn btn-default" onclick="next()">
                Next
            </button>
        </span>
    </div>
</footer>

<script>
    function next() {
        submit();
    }

    function submit() {
        document.getElementsByTagName("form")[0].submit();
    }

    function back() {
        document.getElementById("BackButtonClicked").value = true;
        submit();
    }
</script>

example/Szl.MvcDemo/Views/Wizard/Step1.cshtml
<p>Step 1</p>

example/Szl.MvcDemo/Views/Wizard/Step2.cshtml
@model Step2ViewModel

<p>Step 2</p>

@Html.LabelFor(model => model.UnblockBlockNodes, "Unblock Blocked Nodes")
@Html.CheckBoxFor(model => model.UnblockBlockNodes)

example/Szl.MvcDemo/Views/Wizard/Step3.cshtml
@model Step3ViewModel
<p>Step 3</p>

@Html.LabelFor(model => model.NumberOfPrograms)
@Html.TextBoxFor(model => model.NumberOfPrograms, new { type="number"})